name: CI

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - maste
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libcmocka-dev
      run: sudo apt-get update && sudo apt-get install -y libcmocka-dev
    - name: make
      run: make
    - name: make test
      run: make test
